---
- hosts: all
  become: true
  vars:
    # install KVM using make deb-pkg
    kvm_install_package: false
  pre_tasks:
    - name: check for virtualization extensions in cpuinfo
      shell: egrep '(vmx|svm)' /proc/cpuinfo

    - name: system upgrade
      apt:
        update_cache: yes
        upgrade: dist

    - name: install useful tools
      package:
        name: "{{ item }}"
      with_items:
        - git
        - htop
        - vim

  roles:
    - kvm
